services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: my_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elastic-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: rest_api_presentacion
    container_name: api
    environment:
      - SPRING_ELASTICSEARCH_REST_URIS=http://my_elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    networks:
      - elastic-net

networks:
  elastic-net:
    driver: bridge
